services:
  - type: web
    name: brain-tumor-classifier-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true